name: Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e ".[dev]"

    - name: Install external dependencies
      run: |
        # Install miniprot
        sudo apt-get update
        sudo apt-get install -y build-essential zlib1g-dev
        git clone https://github.com/lh3/miniprot.git
        cd miniprot && make && sudo cp miniprot /usr/local/bin/

        # Install pyhmmer
        python -m pip install pyhmmer

    - name: Run unit tests
      run: |
        pytest tests/test_*.py -v --cov=buscolite --cov-report=xml

    - name: Run integration tests without external dependencies
      run: |
        pytest tests/integration/test_buscolite_cli.py tests/integration/test_buscolite_api.py -v

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e ".[dev]"

    - name: Run pre-commit
      uses: pre-commit/action@v3.0.0
